[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino

; A definição oficial ativa a PSRAM OPI da variante N8R8. A flag deixa a
; intenção explícita para o código e facilita o diagnóstico durante o estudo.
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0

monitor_speed = 115200
upload_speed = 921600

; IMPORTANTE:
; Nao forcamos flash_mode/partitions aqui.
; O board oficial do PlatformIO ja define as caracteristicas corretas
; da Freenove ESP32-S3 WROOM N8R8 (8 MB Flash + 8 MB PSRAM).

# Sistema de arquivos usado pela pasta data/
board_build.filesystem = littlefs
